### ISSUE TITLE
fatal error: 'remote-ext.h' file not found  -   High Sierra

### ISSUE THREAD

**Issue by chmedly** [audioscience/avdecc-lib#388]
Trying to build on Macos High Sierra.  I'm getting this error on the "make" command.  Perhaps there's something I'm just not getting?

**Comment by vronchetti** [comment]
Hi @chmedly,

This issue has been fixed on the staging branch.  [Here](https://github.com/audioscience/avdecc-lib/commit/0be4fee44d51459dcf66d7c159b14403c9f6772b#diff-c6278dbb531648d06f5b9ee60c19d249L32 ) is the fix.  Please let me know if you have any other questions.

**Comment by chmedly** [comment]
Sorry, I may need some hand-holding here.  I modified the file "net_interface_imp.h" based on the changes in green that you linked to.  Then I tried the cmake and make commands again.  I still get the same error.  I also get the following warning when running the cmake.  Perhaps this has something to do with it?  I'm still at the point where I don't know what I don't know about this code.  

```
  MACOSX_RPATH is not specified for the following targets:

   avdecc-lib_controller
```

**Comment by vronchetti** [comment]
@chmedly No worries -  You need to remove line [no. 32](https://github.com/audioscience/avdecc-lib/blob/master/controller/lib/src/osx/net_interface_imp.h#L32). 

```cpp
#define HAVE_REMOTE
```

 Does the staging branch work for you?

**Comment by andrew-elder** [comment]
@chmedly - do you know how to check out git branches?

**Comment by chmedly** [comment]
@andrew-elder - I think so?  I'm not sure I know how to get it via _git clone_ but I downloaded the zip of the staging branch. 

@vronchetti  - I ran cmake and then make with the staging zip.  I got this error - 

**fatal error: 
      'jdksavdecc_acmp.h' file not found**

**Comment by chmedly** [comment]
I just tried it by using the main avdecc-lib and commenting out line 32 as vronchetti indicated.  I get the same error as I do with the staging branch.   
I must be doing something wrong.

**Comment by vronchetti** [comment]
> I ran cmake and then make with the staging zip. I got this error -
> fatal error: 'jdksavdecc_acmp.h' file not found

@chmedly,  you are missing the jdksavdecc submodule:

```
cd avdecc-lib
git submodule init
git submodule update
```

**Comment by chmedly** [comment]
It took me a minute to realize I needed to put the git folder in the directory (for the staging branch) but I got it to build.  Thanks!

**Comment by andrew-elder** [comment]
Great!
